### ISSUE TITLE
uuid ^2.2.2 which depends on crypto ^2.0.0

### ISSUE THREAD

**Issue by PieterHartzer** [krista-koivisto/short_uuid#1]
I am not able to use short_uuids with source_gen since flutter upgrade.

> Because no versions of source_gen match >1.0.0 <2.0.0 and source_gen 1.0.0 depends on build ^2.0.0, source_gen ^1.0.0 requires build ^2.0.0.
> 
> And because no versions of build match >2.0.0 <3.0.0 and build 2.0.0 depends on crypto ^3.0.0, source_gen ^1.0.0 requires crypto ^3.0.0.
> 
> And because every version of short_uuids depends on uuid ^2.2.2 which depends on crypto ^2.0.0, source_gen ^1.0.0 is incompatible with short_uuids.

**Comment by applifi** [comment]
Thank you for raising this issue. I will look into it!

**Comment by raccoons-are-goofy** [comment]
Thank you for raising this issue. I will look into it!

**Comment by raccoons-are-goofy** [comment]
Sorry this took so long to look into. The issue has now been fixed with short_uuids release 3.0.0. It also includes null-safety support. Update your `pubspec.yaml` line to `short_uuids: ^3.0.0` to fix.
